configfile: "config/config.yaml"


accession = config["accession"]
chromosome_conf = config["sample"]
genome_config = config["sample"]
candidate = config["candidate"]
# chr_chromosomes = "chr" + str(config["chromosome"])


scattergather:
    split_candidates=4,


include: "rules/align_reads.smk"
include: "rules/avg_bedgraph.smk"
include: "rules/candidates.smk"
include: "rules/get_data.smk"


report: "report/workflow.rst"


rule all:
    input:
        # expand("results/{SRA}/number_bases.csv", SRA=accession),
        # expand("results/{SRA}/ratio_barplot.html", SRA=accession),
        expand("results/{SRA}/datavzrd-reports/", SRA=accession),


rule find_bases:
    input:
        bedGraph=expand(
            "resources/bed_avg_{chromosome}.bedGraph", chromosome=config["chromosome"]
        ),
        aligned_reads="resources/{SRA}/candidate_specific/alignment_{scatteritem}.bam",
        aligned_reads_index="resources/{SRA}/candidate_specific/alignment_{scatteritem}.bam.bai",
        # aligned_reads="resources/{SRA}/aligned-reads-focused.sam",
        # candidates="resources/candidates_{scatteritem}.vcf",
        # candidates="resources/candidates_filtered_{scatteritem}.vcf",
    output:
        "results/{SRA}/all_pos_to_base/number_bases_{scatteritem}.csv",
    conda:
        "envs/varlociraptor.yaml"
    params:
        pipeline_path=config["pipeline_path"],
        deamination_path=config["deamination_path"],
    log:
        "logs/find_bases_{SRA}_{scatteritem}.log",
    shell:
        """
        cd {params.deamination_path}
        cargo run -- find-bases {params.pipeline_path}{input.aligned_reads} {params.pipeline_path}{input.bedGraph} {params.pipeline_path}{output}
       """


rule gather_calls:
    input:
        gather.split_candidates(
            "results/{{SRA}}/all_pos_to_base/number_bases_{scatteritem}.csv"
        ),
    output:
        "results/{SRA}/number_bases_concat.csv",
    shell:
        """
        echo methylation_status,direction,orig_base,A,C,G,T,N > {output}
        cat {input} >> {output}
        """


rule number_nucleotides:
    input:
        "results/{SRA}/number_bases_concat.csv",
    output:
        "results/{SRA}/number_bases.csv",
    conda:
        "envs/plot.yaml"
    log:
        "logs/number_nucleotides_{SRA}.log",
    script:
        "scripts/merge_nucleotides.py"


rule plot_number_nucleotides:
    input:
        "results/{SRA}/number_bases.csv",
    output:
        "results/{SRA}/ratio_barplot.json",
    conda:
        "envs/plot.yaml"
    log:
        "logs/plot_number_nucleotides_{SRA}.log",
    script:
        "scripts/barplot.py"


# Postprocessing GO Enrichment Data
# Generating Meta Comparison Datavzrd Reports
rule number_nucleotides_datavzrd:
    input:
        config="workflow/resources/datavzrd/number_nucleotides-template.yaml",
        table="results/{SRA}/number_bases.csv",
        plot="results/debug/ratio_barplot.json",
    output:
        report(
            directory("results/{SRA}/datavzrd-reports/"),
            category=lambda wildcards: f"Datavzrd {wildcards.SRA}",
        ),
    # params:
    # pathway_db=config["enrichment"]["spia"]["pathway_database"],
    # species=config["resources"]["ref"]["species"],
    log:
        "logs/number_nucleotides_datavzrd_{SRA}.log",
    wrapper:
        "v5.5.0/utils/datavzrd"


# rule assign_bases:
#     input:
#         bedGraph=expand(
#             "resources/bed_avg_{chromosome}.bedGraph", chromosome=config["chromosome"]
#         ),
#         # bedGraph="resources/alignments_CpG.bedGraph",
#         ref_bases="results/{SRA}/pos_to_bases.txt",
#     output:
#         "results/{SRA}/assigned_bases.txt",
#     conda:
#         "envs/varlociraptor.yaml"
#     params:
#         pipeline_path=config["pipeline_path"],
#         deamination_path=config["deamination_path"],
#     log:
#         "logs/assign_bases_{SRA}.log",
#     shell:
#         """
#         cd {params.deamination_path}
#         cargo run  -- assign-bases {params.pipeline_path}{input.bedGraph} {params.pipeline_path}{input.ref_bases} {params.pipeline_path}{output}
#         """
# rule plot_methylation_status:
#     input:
#         bedGraph=expand(
#             "resources/bed_avg_{chromosome}.bedGraph", chromosome=config["chromosome"]
#         ),
#         # bedGraph="resources/bed_avg.bedGraph",
#         # bedGraph="resources/alignments_CpG.bedGraph",
#         ref_bases="results/{SRA}/pos_to_bases.txt",
#     output:
#         unmeth="results/{SRA}/unmeth.png",
#         meth="results/{SRA}/meth.png",
#     conda:
#         "envs/plot.yaml"
#     params:
#         pipeline_path=config["pipeline_path"],
#         deamination_path=config["deamination_path"],
#     log:
#         "logs/plot_methylation_status{SRA}.log",
#     script:
#         "scripts/plot_methylation_status.py"
# # rule gather_calls:
# #     input:
# #         gather.split_candidates("results/pos_to_bases_{scatteritem}.txt")
# #     output:
# #         "resources/pos_to_bases.txt"
# #     shell:
# #         "cat {input} > {output}"
