sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"
  chromosome: "21"

candidate: 1
chromosome: 21
# varlo_path: "~/Documents/Promotion/deamination-varlo/varlociraptor/"
# pipeline_path: "~/Documents/Promotion/deamination-pipeline/"
# deamination_path: "~/Documents/Promotion/deamination/"


varlo_path: "/projects/koesterlab/benchmark-methylation/deamination-varlo/varlociraptor/"
pipeline_path: "/projects/koesterlab/benchmark-methylation/deamination-pipeline/"
deamination_path: "/projects/koesterlab/benchmark-methylation/deamination/"


read_type: "Illumina"
max_read_length: 100000

# Nicht bisulfitbehandelte Referenzdaten: SRR1766444 (1.18 GB)
accession: 
  # - "debug"
  # - "example"
  # - "test_reverse"
  # - "SRR12898274"
  # - "SRR1766444"
  # - "SRR1766451"
  # - "SRR12898336"
  # - "SRR1766456"
  # - "SRR1766495"
  # - "SRR1766502"
  # - "SRR1766555"
  # - "SRR1766504"
  # - "SRR1766492"
  # - "SRR1766528"
  - "HG002_HiSeq30x_subsampled"

bedGraphs_HG002:
  - GSM5649436_TruSeq_HG002_LAB01_REP02
  - GSM5649437_TruSeq_HG002_LAB01_REP01
  - GSM5649458_SPLAT_HG002_LAB01_REP02
  - GSM5649459_SPLAT_HG002_LAB01_REP01
  - GSM5649479_MethylSeq_HG002_LAB01_REP02
  - GSM5649480_MethylSeq_HG002_LAB01_REP01
  - GSM5649515_EMSeq_HG002_LAB02_REP02
  - GSM5649517_EMSeq_HG002_LAB02_REP01
  - GSM5649518_EMSeq_HG002_LAB01_REP02
  - GSM5649520_EMSeq_HG002_LAB01_REP01
  - GSM5649543_TrueMethylOX_HG002_LAB01_REP02
  - GSM5649545_TrueMethylOX_HG002_LAB01_REP01
  - GSM5649565_TrueMethylBS_HG002_LAB01_REP02
  - GSM5649567_TrueMethylBS_HG002_LAB01_REP01
  - GSM5649568_EPIC_HG002_LAB01_REP02
  - GSM5649573_EPIC_HG002_LAB01_REP01
