sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"
  chromosome: "1"


varlo_path: "~/Documents/Promotion/deamination-varlo/varlociraptor/"
pipeline_path: "~/Documents/Promotion/deamination-pipeline/"

# varlo_path: "/projects/koesterlab/benchmark-methylation/deamination-varlo/varlociraptor/"
# pipeline_path: "/projects/koesterlab/benchmark-methylation/deamination-pipeline/"

# varlo_path: "/local/work/aprinz/deamination-varlo/varlociraptor/"
# pipeline_path: "/local/work/aprinz/deamination-pipeline/"


read_type: "Illumina"
# accession: "SRR13051250"

accession: "SRR1766443"


bedGraphs_HG002:
  - GSM5649436_TruSeq_HG002_LAB01_REP02
  - GSM5649437_TruSeq_HG002_LAB01_REP01
  - GSM5649458_SPLAT_HG002_LAB01_REP02
  - GSM5649459_SPLAT_HG002_LAB01_REP01
  - GSM5649479_MethylSeq_HG002_LAB01_REP02
  - GSM5649480_MethylSeq_HG002_LAB01_REP01
  - GSM5649515_EMSeq_HG002_LAB02_REP02
  - GSM5649517_EMSeq_HG002_LAB02_REP01
  - GSM5649518_EMSeq_HG002_LAB01_REP02
  - GSM5649520_EMSeq_HG002_LAB01_REP01
  - GSM5649543_TrueMethylOX_HG002_LAB01_REP02
  - GSM5649545_TrueMethylOX_HG002_LAB01_REP01
  - GSM5649565_TrueMethylBS_HG002_LAB01_REP02
  - GSM5649567_TrueMethylBS_HG002_LAB01_REP01
  - GSM5649568_EPIC_HG002_LAB01_REP02
  - GSM5649573_EPIC_HG002_LAB01_REP01
